### ISSUE TITLE
Plan for 20.04 LTS?

### ISSUE THREAD

**Issue by axi92** [core-process/linux-unattended-installation#22]
Hey I am looking forward to an 20.04 LTS Version =)

**Comment by dahLucky** [comment]
You can use the 18.04 script. In my case the [Workaround for hanging grub installation](https://github.com/core-process/linux-unattended-installation/commit/3b40a50e12a17b7c6346b107cd06593bcdc5e156) caused the grub install to fail, so I reverted back to the initial version. 

You'll also need to adjust the SOURCE_ISO_URL (Line 28 in build-iso.sh) to http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/mini.iso 

Otherwise all works as expected. Great script!

**Comment by hadrien-toma** [comment]
See #23
